[package]
name = "rust-ttt"
version = "0.1.0"
edition = "2024"

[dependencies]
abort = "0.1.3"
anyhow = "1.0.98"
pcap = "2.2.0"
pnet= "0.35.0"
pnet_transport = "0.35.0"
rand = "0.9.1"
twox-hash = "2.1.0"
